title: Martin's Developer Notebook
show_downloads: false
description: Code from every part of my experiences, C#, Unity, Office Automation and other things...
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

remote_theme: "godalming123/minimal"
plugins:
- jekyll-remote-theme

github:
  is_user_page: true

color-scheme: auto-default-dark # ["dark", "light", "auto" or "auto-default-dark"]